"""add counts to order table

Revision ID: 12abe9c79b96
Revises: 053f1bed64a7
Create Date: 2021-03-30 18:24:55.484277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12abe9c79b96'
down_revision = '053f1bed64a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('counts', sa.Numeric(), nullable=True, comment='生码量'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'counts')
    # ### end Alembic commands ###
