"""update order table

Revision ID: 1d95ce6247c5
Revises: 213d2f3c7190
Create Date: 2021-03-29 17:02:43.027321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d95ce6247c5'
down_revision = '213d2f3c7190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code_sn', sa.String(length=64), nullable=True, comment='生码编号'),
    sa.Column('company_code', sa.String(length=64), nullable=True, comment='商户名称'),
    sa.Column('relevance_type', sa.SmallInteger(), nullable=True, comment='关联 before 1 前关联 after 2 后关联'),
    sa.Column('code_type', sa.SmallInteger(), nullable=True, comment='码类型 standard 1 标准码 group 2 套标'),
    sa.Column('code_config', sa.Text(), nullable=True, comment='码配置'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='生码状态 wait 0 等待 begin 1 开始 done 2 完成 cancel 3 取消 fail 4 失败'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_code'], ['companies.company_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_code_sn'), 'orders', ['code_sn'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_index('ix_code_orders_code_sn', table_name='code_orders')
    op.drop_index('ix_code_orders_id', table_name='code_orders')
    op.drop_table('code_orders')
    op.add_column('companies', sa.Column('company_full_name', sa.String(length=128), nullable=True, comment='公司名称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_full_name')
    op.create_table('code_orders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code_sn', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='生码编号'),
    sa.Column('company_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='商户名称'),
    sa.Column('relevance_type', sa.SMALLINT(), autoincrement=False, nullable=True, comment='关联 before 1 前关联 after 2 后关联'),
    sa.Column('code_type', sa.SMALLINT(), autoincrement=False, nullable=True, comment='码类型 standard 1 标准码 group 2 套标'),
    sa.Column('code_config', sa.TEXT(), autoincrement=False, nullable=True, comment='码配置'),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True, comment='生码状态 wait 0 等待 begin 1 开始 done 2 完成 cancel 3 取消 fail 4 失败'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_code'], ['companies.company_code'], name='code_orders_company_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='code_orders_pkey')
    )
    op.create_index('ix_code_orders_id', 'code_orders', ['id'], unique=False)
    op.create_index('ix_code_orders_code_sn', 'code_orders', ['code_sn'], unique=True)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_code_sn'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
