"""create code_order table

Revision ID: 213d2f3c7190
Revises: 65e7156abfe9
Create Date: 2021-03-29 16:21:41.210190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d2f3c7190'
down_revision = '65e7156abfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code_sn', sa.String(length=64), nullable=True, comment='生码编号'),
    sa.Column('company_code', sa.String(length=64), nullable=True, comment='商户名称'),
    sa.Column('relevance_type', sa.SmallInteger(), nullable=True, comment='关联 before 1 前关联 after 2 后关联'),
    sa.Column('code_type', sa.SmallInteger(), nullable=True, comment='码类型 standard 1 标准码 group 2 套标'),
    sa.Column('code_config', sa.Text(), nullable=True, comment='码配置'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='生码状态 wait 0 等待 begin 1 开始 done 2 完成 cancel 3 取消 fail 4 失败'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_code'], ['companies.company_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_orders_code_sn'), 'code_orders', ['code_sn'], unique=True)
    op.create_index(op.f('ix_code_orders_id'), 'code_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_orders_id'), table_name='code_orders')
    op.drop_index(op.f('ix_code_orders_code_sn'), table_name='code_orders')
    op.drop_table('code_orders')
    # ### end Alembic commands ###
