"""init table

Revision ID: 65e7156abfe9
Revises: 
Create Date: 2021-03-29 15:56:13.794502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e7156abfe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid_code', sa.String(length=64), nullable=True, comment='生码系统编号'),
    sa.Column('company_code', sa.String(length=64), nullable=True, comment='商户编号'),
    sa.Column('company_name', sa.String(length=64), nullable=True, comment='商户名称'),
    sa.Column('code_table_name', sa.String(length=64), nullable=True, comment='商户码表'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_uuid_code'), 'companies', ['uuid_code'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_code', sa.String(length=64), nullable=True, comment='设备编号'),
    sa.Column('equipment_name', sa.String(length=64), nullable=True, comment='设备名称'),
    sa.Column('equipment_desc', sa.String(length=125), nullable=True, comment='设备描述'),
    sa.Column('remarks', sa.String(length=125), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='激活状态'),
    sa.Column('equipment_key', sa.String(length=256), nullable=True, comment='通信密钥'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_equipment_code'), 'equipments', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限 name'),
    sa.Column('desc', sa.String(length=64), nullable=True, comment='权限描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单 name'),
    sa.Column('desc', sa.String(length=64), nullable=True, comment='菜单描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色 name'),
    sa.Column('desc', sa.String(length=64), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=120), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='Email'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='激活状态'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='超级管理员'),
    sa.Column('access_token', sa.String(length=300), nullable=True, comment='access token'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('menu_identity',
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], )
    )
    op.create_table('role_identity',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('role_identity')
    op.drop_table('menu_identity')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_equipment_code'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_companies_uuid_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
