"""update menus table

Revision ID: 7bc89ddcb563
Revises: e22cccd492b6
Create Date: 2021-03-25 17:14:56.126673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc89ddcb563'
down_revision = 'e22cccd492b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
