"""menu relationship update

Revision ID: dc9ffe041279
Revises: f18de6400e25
Create Date: 2021-03-23 13:44:58.853194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9ffe041279'
down_revision = 'f18de6400e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
