"""update menus table

Revision ID: e22cccd492b6
Revises: befac4002c7f
Create Date: 2021-03-25 10:27:41.779446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22cccd492b6'
down_revision = 'befac4002c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'menus', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'parent_id')
    # ### end Alembic commands ###
