"""add menu, company and equipment table

Revision ID: f18de6400e25
Revises: 2003a88f04c8
Create Date: 2021-03-23 13:37:00.133370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18de6400e25'
down_revision = '2003a88f04c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('uuid_code', sa.String(length=64), nullable=False, comment='生码系统编号'),
    sa.Column('company_code', sa.String(length=64), nullable=True, comment='商户编号'),
    sa.Column('company_name', sa.String(length=64), nullable=True, comment='商户名称'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('uuid_code')
    )
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_index(op.f('ix_companies_uuid_code'), 'companies', ['uuid_code'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_code', sa.String(length=64), nullable=True, comment='设备编号'),
    sa.Column('equipment_name', sa.String(length=64), nullable=True, comment='设备名称'),
    sa.Column('equipment_desc', sa.String(length=125), nullable=True, comment='设备描述'),
    sa.Column('remarks', sa.String(length=125), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='激活状态'),
    sa.Column('equipment_key', sa.String(length=256), nullable=True, comment='通信密钥'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_equipment_code'), 'equipments', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单 name'),
    sa.Column('desc', sa.String(length=64), nullable=True, comment='菜单描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('menu_identity',
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_identity')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_equipment_code'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_companies_uuid_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
